name: Run Unit Tests for Geometric Library

on:
  push:
    branches:
      - laba_4 
  pull_request:
    branches:
      - laba_4 
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  
          
      # Шаг 3: Запуск тестов
      - name: Run unit tests
        run: |
          python -m unittest discover -s . -p "unittest_*.py"
